import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from "../styles/Home.module.css"
import React, {useState} from 'react'
import Fetch from 'isomorphic-unfetch';

console.log("htmlのロードが完了しました。")

export default function Home() {

  const [use, setUse] = useState("ありません。");
  const [count, setCount] = useState(0);



  return (
    <div>
      <Head>
        <title>HTML訓練</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
    <button>
      <Link href="/new">
        <a>こちら</a>
      </Link>
    </button>


        <div>ユーザー</div>
        <div>部門</div>
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>誕生日</th>
                <th>性別</th>
                <th>メール</th>
                <th>職種</th>
                <th>登録日</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td>value.id</td>
                <td>value.birth</td>
                <td>value.gender</td>
                <td>value.mail</td>
                <td>value.job</td>
                <td>value.work_at</td>
              </tr>
            </tbody>
          </table>
      </main>
      </div>
  )
}
