import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from "../styles/Home.module.css"
import React, {useState} from 'react'
import Fetch from 'isomorphic-unfetch';

console.log("htmlのロードが完了しました。")

export default function Home() {

  return (
    <div>
      <Head>
        <title>HTML訓練</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <main>
      <button>
      <Link href="/index">
        <a>こちら</a>
      </Link>
    </button>
        <div>
          名前
          <input></input>
        </div>
        <div>
          誕生日
          <input></input>
        </div>
        <div>
          性別
          <input></input>
          </div>
        <div>
          メール
          <input></input>
          </div>
        <div>
          職種
          <input></input>
          </div>
        <div>
          登録日
          <input></input>
          </div>
          <button>登録</button>
      </main>
      </div>
  )
}
