import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css"
import React, {useState} from 'react'
import Fetch from 'isomorphic-unfetch';

console.log("htmlのロードが完了しました。")

export default function Home() {

const [use, setUse] = useState("ありません。");
const [count, setCount] = useState(0);



return (
    <div>
        <Head>
        <title>HTML訓練</title>
        <meta name="description" content="Generated by create next app" />
        </Head>

      <main>
        <div>
          <select id = "select_city">
            <option value ="1">東京</option>
            <option value="2">大阪</option>
            <option value="3">札幌</option>
          </select>
          <div>
            <div>天気情報</div>
            <div id="weather-area">なし</div>
            <div id="weather-temp">なし</div>
            <div id="weather-humidity">なし</div>
            <div id="weather-pressure">なし</div>
            <div id="weather-description">なし</div>
        </div>
        </div>
        <div>姉川です。HELLO WORLD!!</div>
          <Image src="/linux_penguin.png" width={505} height={220} />
        <div>
          <label>名前を入力:</label>setCount
            <input type="text" placeholder="Sota Anegawa"></input>
        </div>
        <div>
          <label>趣味を選択:</label>
            <select id = "hobby" onChange = {() => {console.log("選ばれた趣味は" + hobby.value); setUse(hobby.value); setCount(count + 1)}}>
              <option>選択してください</option>
              <option value="カポエイラです。">カポエイラ</option>
              <option value="ラップバトルです。">ラップバトル</option>
              <option value="爆竹作りです。">爆竹作り</option>
              <option value="アルゴリズム研究です。">アルゴリズム研究</option>
              <option value="喧嘩です。">喧嘩</option>
            </select>
        </div>
        <div id = "selected hobby">
          現在選択されている趣味は{ use }
        </div>
        <div>
          趣味は{ count }回選択されました。
        </div>
        <div>
          <button onClick = {() => console.log('クリックイベントが動作しました。')}>
            js動作テストp
          </button>
        </div>
      </main>
    </div>
  )
}
